//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _30cinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaaEntities : DbContext
    {
        public CinemaaEntities()
            : base("name=CinemaaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HALL> HALL { get; set; }
        public virtual DbSet<MHS> MHS { get; set; }
        public virtual DbSet<SESSION> SESSION { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<MHSS> MHSS { get; set; }
        public virtual DbSet<SEAT> SEAT { get; set; }
        public virtual DbSet<MOVIE> MOVIE { get; set; }
        public virtual DbSet<TICKETDETAILS> TICKETDETAILS { get; set; }
    }
}
