//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _30cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MHS()
        {
            this.MHSS = new HashSet<MHSS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MOVIEID { get; set; }
        public Nullable<int> HALLID { get; set; }
        public Nullable<int> SESSIONID { get; set; }
    
        public virtual HALL HALL { get; set; }
        public virtual SESSION SESSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MHSS> MHSS { get; set; }
        public virtual MOVIE MOVIE { get; set; }
    }
}
