//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _30cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETDETAILS
    {
        public int ID { get; set; }
        public Nullable<int> TICKETID { get; set; }
        public Nullable<bool> PAYMENTTYPE { get; set; }
        public Nullable<decimal> PAYMENTTOTAL { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual TICKET TICKET { get; set; }
    }
}
